
trigger:
  branches:
    include:
    - feature/*
    - features/*
    - fix/*
#- main


pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Packer_Build
    pool: 
      name: Default
    steps:
    - task: AzureCLI@2
      displayName: Packer Build
      inputs:
        azureSubscription: 'Azure service connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          packer build ubuntu.json
