# pipeline to build image via packer
trigger:
  branches:
    include:
    - feature/*
    - features/*
    - fix/*
#- main


pool:
  vmImage: ubuntu-latest

steps:
- script: env | sort
  displayName: 'Dump environment'
- task: AzureCLI@2
  displayName: Packer Build
  inputs:
    azureSubscription: 'Azure service connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo Hello
      az account show | jq -r .tenantId
      MY_TENANT_ID=$(az account show | jq -r .tenantId)
      # SUBSCRIPTION_ID=$(az account show | jq -r .Id)
      # packer build -var 'client_id=foo' -var 'client_secret=bar' -var "tenant_id=${TENANT_ID}" -var "subscription_id=${SUBSCRIPTION_ID}" ubuntu.json

# stages:
# - stage: Build
#   jobs:
#   - job: Packer_Build
#     pool: 
#       name: Default
#     steps:
#     - task: AzureCLI@2
#       displayName: Packer Build
#       inputs:
#         azureSubscription: 'Azure service connection'
#         scriptType: bash
#         scriptLocation: inlineScript
#         inlineScript: |
#           packer build ubuntu.json
