# pipeline to build image via packer
trigger:
  branches:
    include:
    - feature/*
    - features/*
    - fix/*
#- main

variables:
  group: builder-vars

pool:
  vmImage: ubuntu-latest

steps:
- script: env | sort
  displayName: 'Dump environment'
- task: AzureCLI@2
  displayName: Packer Build
  env:
    MY_CLIENT_ID: $(client-id)
    MY_CLIENT_SECRET: $(client-secret)
  inputs:
    azureSubscription: 'Azure service connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      MY_TENANT_ID=$(az account show | jq -r .tenantId)
      MY_SUBSCRIPTION_ID=$(az account show | jq -r .id)
      # MY_CLIENT_ID=$(az keyvault secret show --vault-name examplekeys --name client-id | jq -r .value)
      # MY_CLIENT_SECRET=$(az keyvault secret show --vault-name examplekeys --name client-secret | jq -r .value)
      echo tenant: $MY_TENANT_ID, sub: ${MY_SUBSCRIPTION_ID}
      echo packer build -var "client_id=${CLIENT_ID}" -var "client_secret=${CLIENT_SECRET}" -var "tenant_id=${MY_TENANT_ID}" -var "subscription_id=${MY_SUBSCRIPTION_ID}" ubuntu.json

# stages:
# - stage: Build
#   jobs:
#   - job: Packer_Build
#     pool: 
#       name: Default
#     steps:
#     - task: AzureCLI@2
#       displayName: Packer Build
#       inputs:
#         azureSubscription: 'Azure service connection'
#         scriptType: bash
#         scriptLocation: inlineScript
#         inlineScript: |
#           packer build ubuntu.json
