# pipeline to build image via packer
trigger:
  branches:
    include:
    - feature/*
    - features/*
    - fix/*
#- main


pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: AzureCLI@2
  displayName: Packer Build
  inputs:
    azureSubscription: 'Azure service connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      packer build ubuntu.json

# stages:
# - stage: Build
#   jobs:
#   - job: Packer_Build
#     pool: 
#       name: Default
#     steps:
#     - task: AzureCLI@2
#       displayName: Packer Build
#       inputs:
#         azureSubscription: 'Azure service connection'
#         scriptType: bash
#         scriptLocation: inlineScript
#         inlineScript: |
#           packer build ubuntu.json
