# pipeline to build image via packer
trigger:
  branches:
    include:
    - feature/*
    - features/*
    - fix/*
#- main

variables:
- group: 'builder-vars'
- name: 'foo'
  value: 'bar'

pool:
  vmImage: ubuntu-latest

steps:
- script: env | sort
  displayName: 'Dump environment'
- task: AzureCLI@2
  displayName: Packer Build
  env:
    MY_CLIENT_ID: $(client-id)
    MY_CLIENT_SECRET: $(client-secret)
    MY_TENANT_ID: $(tenant-id)
    MY_SUBSCRIPTION_ID: $(subscription-id)
  inputs:
    azureSubscription: 'Azure service connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      MY_XXTENANT_ID=$(az account show | jq -r .tenantId)
      MY_XXSUBSCRIPTION_ID=$(az account show | jq -r .id)
      packer build -var "client_id=${MY_CLIENT_ID}" -var "client_secret=${MY_CLIENT_SECRET}" -var "tenant_id=${MY_TENANT_ID}" -var "subscription_id=${MY_SUBSCRIPTION_ID}" ubuntu.json

# stages:
# - stage: Build
#   jobs:
#   - job: Packer_Build
#     pool: 
#       name: Default
#     steps:
#     - task: AzureCLI@2
#       displayName: Packer Build
#       inputs:
#         azureSubscription: 'Azure service connection'
#         scriptType: bash
#         scriptLocation: inlineScript
#         inlineScript: |
#           packer build ubuntu.json
