---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      yum: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          enabled: yes
          state: started